name: Deploy Development

on:
  push:
    branches: [development]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: 12

      - run: npm install

      - run: npm run publish:dev
        env:
          AZURE_DEVOPS_EXT_PAT: ${{ secrets.PAT_MARKETPLACE }}

      - uses: actions/upload-artifact@v2
        with:
          name: VSIX
          path: out/*.vsix

